version: '2'

services:
  enterpriseready-www:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8888:1313"
    environment:
      - HUGO_WATCH=true
      - HUGO_BASEURL=http://localhost:8888
    volumes:
      - ./site:/src
      - ./content:/src/content
      - ./hugo-config/enterpriseready.toml:/src/config.toml
    networks:
      internal:
        ipv4_address: 172.16.145.112

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.145.0/24
        gateway: 172.16.145.254
  default:
    external:
      name: bridge
