name = "EnterpriseReady"
license = "Apache 2.0"
min_version = 0.16

[author]
  name = "Replicated, Inc."
  homepage = "https://www.replicated.com"

[original]
  name = "Mathieu Cornic"
  homepage = "http://matcornic.github.io/"
